Repository prgrms-web-devcourse-final-project/WEB4_5_CodeNBug_BE, pull requests merged in 2025-04, with the labels that each got.

#7 Update issue templates
  .github/ISSUE_TEMPLATE/♻️-리팩토링-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/✨-기능-이슈-템플릿.md
  .github/ISSUE_TEMPLATE/🐛-버그-이슈-템플릿.md
  .github/workflows/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  service/main-server/Dockerfile
  service/main-server/src/main/resources/application.yml
  service/queue-server/Dockerfile
  service/queue-server/src/main/resources/application.yml
Labels: documentation

#22 Feat/매니저 행사 생성
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/controller/ManagerController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/EventRegisterRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/EventRegisterResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/Event.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/EventStatus.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/EventStatusEnum.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/EventType.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/repository/EventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/repository/EventTypeRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/ManagerService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/SeatLayout.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/repository/SeatGradeRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/repository/SeatLayoutRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/repository/SeatRepository.java
Labels: enhancement

#24 Feat: 알림 기능 관련 Entity 생성
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/entity/Notification.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/entity/NotificationEnum.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/entity/NotificationSubscription.java
Labels: enhancement

#25 Feat: 사용자 인증 - 환경설정
  service/main-server/.gitignore
  service/main-server/build.gradle
  service/main-server/src/main/java/org/codeNbug/mainserver/MainServerApplication.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/User/temp.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/EventStatus.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/controller/UserController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/entity/User.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/repository/UserRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/UserService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/config/CorsProperties.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/config/JwtConfig.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/config/SecurityConfig.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/filter/JwtAuthenticationFilter.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/service/CustomUserDetailsService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/temp.java
  service/main-server/src/main/resources/application.yml
Labels: feat

#10 Feat : 대기열 추가
  service/main-server/src/main/java/org/codeNbug/mainserver/user/entity/User.java
  service/main-server/src/main/java/org/codeNbug/mainserver/user/service/UserService.java
  service/queue-server/settings.gradle
  service/queue-server/src/main/java/org/codeNbug/queueserver/global/GlobalConfig.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/controller/WaitingQueueController.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/service/SseEmitterService.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/service/WaitingQueueService.java
Labels: enhancement

#36 Feat/좌석 선택
  service/main-server/build.gradle
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/controller/SeatController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/dto/SeatSelectRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/dto/SeatSelectResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/Seat.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/SeatGrade.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/SeatGradeEnum.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/SeatLayout.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/RedisListenerService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/RedisLockService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/config/RedisConfig.java
Labels: feat

#30 Feat/사용자 로그인 회원가입
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/controller/UserController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/dto/request/LoginRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/dto/request/SignupRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/dto/response/LoginResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/dto/response/SignupResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/UserService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/dto/Empty.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/dto/RsData.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/exception/GlobalExceptionHandler.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/exception/globalException/DuplicateEmailException.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/exception/security/AuthenticationFailedException.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/config/SecurityConfig.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/filter/JwtAuthenticationFilter.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/service/CustomUserDetails.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/service/CustomUserDetailsService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/util/CookieUtil.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/util/JwtConfig.java
  service/main-server/src/main/resources/application.yml
Labels: feat

#14 Feat/대기열 정보 전송
  service/queue-server/src/main/java/org/codeNbug/queueserver/external/redis/RedisConfig.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/global/GlobalConfig.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/service/SseEmitterService.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/service/WaitingQueueService.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/thread/QueueInfoThread.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/thread/ThreadConfig.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/thread/WaitingControllerThread.java
Labels: enhancement

#42 Feat: RsData 응답 구조 확장 및 페이징 메타데이터 추가
  service/main-server/src/main/java/org/codeNbug/mainserver/global/dto/PageMetadata.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/dto/RsData.java
Labels: enhancement

#39 Feat/좌석 취소
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/controller/SeatController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/dto/SeatCancelRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/Seat.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatService.java
Labels: enhancement, feat

#43 Feat/좌석 조회
  service/main-server/src/main/java/org/codeNbug/mainserver/MainServerApplication.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/controller/SeatController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/dto/SeatLayoutResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/SeatGradeEnum.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/repository/SeatRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/exception/GlobalExceptionHandler.java
Labels: enhancement, feat

#44 Feat: 사용자 토큰관리(access token, refresh token)
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/controller/TokenController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/controller/UserController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/dto/response/LoginResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/UserService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/Redis/config/RedisConfig.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/Redis/repository/RedisRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/Redis/service/TokenService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/exception/security/InvalidTokenException.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/config/SecurityConfig.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/util/CookieUtil.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/util/JwtConfig.java
Labels: feat

#47 Feat: 이벤트 신규 등록 기능 구현 및 좌석/좌석등급/레이아웃 저장 로직 개선
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/controller/ManagerController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/EventRegisterRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/EventRegisterResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/layout/LayoutDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/layout/PriceDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/layout/SeatInfoDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/Event.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/EventType.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/repository/EventTypeRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/ManagerService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/Seat.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/SeatGrade.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/repository/SeatRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/config/SecurityConfig.java
  service/main-server/src/main/resources/application.yml
Labels: enhancement

#51 Feat: 사용자 이메일 인증
  service/main-server/build.gradle
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/EmailConfig.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/controller/EmailController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/dto/EmailDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/entity/Email.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/repository/EmailRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/EmailService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/Redis/config/RedisConfig.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/Redis/repository/RedisRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/security/config/SecurityConfig.java
  service/main-server/src/main/resources/templates/mail.html
Labels: feat
