Repository prgrms-web-devcourse-final-project/WEB4_5_CodeNBug_BE, pull requests merged in 2025-05, with the labels that each got.

#142 Bug: 사용자 오류
  .github/workflows/deploy.yml
  service/common/src/main/java/org/codenbug/common/util/CookieUtil.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/controller/UserController.java
  service/main-server/src/main/resources/application-prod.yml
  service/main-server/src/main/resources/application.yml
  service/user/src/main/java/org/codenbug/user/sns/service/OauthService.java
Labels: bug

#145 Feat/행사 리스트 조회
  .gitignore
  build.gradle
  service/main-server/build.gradle
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/controller/EventController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/EventRegisterResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/request/EventListFilter.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/response/EventListResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/CommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/CostRange.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/Event.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/EventInformation.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/EventStatusEnum.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/EventType.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/Location.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/JpaCommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/QueryDslCommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/CommonEventService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/EventEditService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/controller/ManagerController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/EventPurchaseResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/EventRegisterRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/ManagerEventListResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/TicketDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/Event.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/EventInformation.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/EventStatusEnum.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/EventType.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/entity/ManagerEvent.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/repository/EventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/repository/EventTypeRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/repository/ManagerEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventDeleteService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventDomainService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventRegisterService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/ManagerEventSearchService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/ManagerPurchasesService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/Seat.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/SeatGrade.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/SeatLayout.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/repository/SeatGradeRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/repository/SeatRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/ticket/entity/Ticket.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/ticket/repository/TicketRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/config/QueryDslConfig.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/exception/GlobalExceptionHandler.java
  service/main-server/src/main/resources/application-prod.yml
  service/message-dispatcher/src/main/java/org/codenbug/messagedispatcher/redis/RedisConfig.java
  service/user/src/main/java/org/codenbug/user/security/config/SecurityConfig.java
Labels: feat

#146 Feat: 사용자 도메인분리
  .github/workflows/deploy.yml
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/sns/controller/OauthController.java
  service/main-server/src/main/resources/application.yml
  service/user/src/main/java/org/codenbug/user/sns/service/OauthService.java
  service/user/src/main/java/org/codenbug/user/sns/util/GoogleOauth.java
  service/user/src/main/java/org/codenbug/user/sns/util/KakaoOauth.java
  service/user/src/main/java/org/codenbug/user/sns/util/SocialOauth.java
Labels: feat

#161 Bug: orderId null 수정
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/entity/Purchase.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseService.java
Labels: bug

#162 Feat: 알림 트랜잭션 동기화
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/dto/NotificationEventDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/entity/Notification.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/entity/NotificationStatus.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/service/NotificationEventService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/service/NotificationService.java
Labels: feat

#169 Refactor/토큰 검증
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/controller/PurchaseController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/controller/SeatController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/RedisLockService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/Redis/entry/EntryTokenValidator.java
  service/main-server/src/main/resources/application-prod.yml
  service/main-server/src/main/resources/application.yml
  service/message-dispatcher/src/main/resources/application.yml
Labels: refactoring

#168 Fix: 실패 메세지의 인코딩 문제로 인한 텍스트 깨짐 현상 해결(SecurityConfig와 .yml에 모두 선언)
  service/main-server/src/main/resources/application.yml
  service/user/src/main/java/org/codenbug/user/security/config/SecurityConfig.java
Labels: bug

#173 fix: 매니저 관리 행사 티켓 구매 내역 조회 시 발생하는 에러 해결 - TicketDto 변환 과정 수정
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/ticket/repository/TicketRepository.java
  service/main-server/src/main/resources/application.yml
  service/message-dispatcher/src/main/resources/application.yml
  service/queue-server/src/main/java/org/codeNbug/queueserver/external/redis/RedisConfig.java
  service/queue-server/src/main/resources/application.yml
Labels: bug

#180 Refactor/결제 부분 취소
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/dto/CancelPaymentRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/dto/CancelPaymentResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/entity/PurchaseCancel.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/external/toss/service/TossPaymentService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/external/toss/service/TossPaymentServiceImpl.java
Labels: refactoring

#181 Feat/카테고리 조회
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/controller/EventController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/CommonEventService.java
  service/user/src/main/java/org/codenbug/user/security/config/SecurityConfig.java
Labels: feat

#178 feat: 남은 좌석수 조회 구현
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/controller/EventController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/CommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/QueryDslCommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/CommonEventService.java
  service/user/src/main/java/org/codenbug/user/security/config/SecurityConfig.java
Labels: feat

#171 Feat/행사 상세 조회
  service/common/src/main/java/org/codenbug/common/util/Util.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/controller/EventController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/EventInfoResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/JpaCommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/CommonEventService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/EventViewCountUpdateScheduler.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/Redis/config/RedisConfig.java
  service/user/src/main/java/org/codenbug/user/security/config/SecurityConfig.java
Labels: feat

#183 Fix: 예외처리 통합
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/controller/UserController.java
Labels: refactoring

#184 fix: 대기열 진입 cors 수정
  .github/workflows/deploy.yml
  service/queue-server/src/main/java/org/codeNbug/queueserver/external/redis/EntryStreamMessageListener.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/global/GlobalConfig.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/controller/WaitingQueueController.java
  service/queue-server/src/main/resources/application.yml
  service/user/src/main/java/org/codenbug/user/security/config/SecurityConfig.java
  service/user/src/main/java/org/codenbug/user/security/filter/JwtAuthenticationFilter.java
Labels: bug

#187 Feat: 사용자 이메인인증수정
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/controller/EmailController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/EmailService.java
  service/main-server/src/main/resources/application.yml
Labels: feat

#186 Feat/매니저 환불
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/controller/ManagerController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/ManagerRefundRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/ManagerRefundResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/repository/PurchaseRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseService.java
Labels: enhancement

#192 Feat/매니저 행사 테스트
  service/main-server/src/main/resources/application.yml
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/controller/ManagerControllerTest.java
Labels: enhancement

#198 fix: 좌석 조회 시 layout도 응답에 포함
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/dto/SeatLayoutResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatService.java
Labels: bug

#196 Feat: 알림 삭제
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/controller/NotificationController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/dto/NotificationDeleteRequestDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/repository/NotificationRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/service/NotificationService.java
Labels: feat

#194 Test/좌석 선택 취소 테스트
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/Event.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/dto/SeatCancelRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/Seat.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/SeatGrade.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/SeatGradeEnum.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/SeatLayout.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/repository/SeatGradeRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/repository/SeatRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatService.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/seat/controller/SeatControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/user/controller/UserControllerTest.java
Labels: test

#208 Test/행사 테스트
  build.gradle
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/controller/EventController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/request/EventListFilter.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/response/EventListResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/CommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/JpaCommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/QueryDslCommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/CommonEventService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/entity/Seat.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/config/AppConfig.java
  service/main-server/src/test/java/org/codeNbug/mainserver/TestConfig.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/event/controller/EventControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/util/TestUtil.java
Labels: bug, test

#211 Refactor/행사 등록
  gradlew
  service/common/src/main/java/org/codenbug/common/util/Util.java
  service/main-server/build.gradle
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/controller/EventController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/EventInfoResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/EventRegisterResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/request/EventListFilter.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/response/EventListResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/Event.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/EventCategoryEnum.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/EventType.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/QueryDslCommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/CommonEventService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/controller/ManagerController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/EventRegisterRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/ManagerEventListResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/repository/EventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/repository/EventTypeRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventDomainService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventEditService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventRegisterService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/ManagerEventSearchService.java
  service/main-server/src/main/resources/application.yml
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/event/controller/EventControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/controller/ManagerControllerTest.java
Labels: enhancement

#212 Bug/삭제된 이벤트 조회
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/QueryDslCommonEventRepository.java
  service/main-server/src/main/resources/application-prod.yml
  service/main-server/src/main/resources/application.yml
Labels: bug

#217 feat: presigned url 방식 이미지 저장 로직 구현
  service/main-server/build.gradle
  service/main-server/src/main/java/org/codeNbug/mainserver/external/image/controller/ImageUploadController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/external/image/dto/ImageUploadRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/external/image/dto/ImageUploadResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/external/image/service/S3PresignedUrlService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/config/S3Config.java
  service/main-server/src/main/resources/application.yml
Labels: enhancement

#218 Test/구매 테스트
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/Event.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/RedisLockService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/external/toss/dto/CanceledPaymentInfo.java
  service/main-server/src/main/java/org/codeNbug/mainserver/external/toss/dto/ConfirmedPaymentInfo.java
  service/main-server/src/main/java/org/codeNbug/mainserver/external/toss/service/TossPaymentServiceImpl.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/purchase/controller/PurchaseControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/seat/controller/SeatControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/util/BaseTestUtil.java
Labels: test

#223 Hotifx : 빌드시 secret이 포함되지 않음
  .github/pull_request_template.md
  .github/workflows/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy.yml
  .github/workflows/disptach-ci.yml
  .github/workflows/main-ci.yml
  .github/workflows/queue-ci.yml
Labels: bug

#222 Test: 알림 테스트 코드 작성
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/notification/controller/NotificationControllerTest.java
Labels: test

#227 Bug/행사 계속 삭제 불가하도록 수정함
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/controller/ManagerController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventDeleteService.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/service/EventDeleteServiceTest.java
Labels: bug

#219 Feat: 관리자 대시보드
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/controller/AdminController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/dto/request/AdminLoginRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/dto/request/AdminSignupRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/dto/request/RoleUpdateRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/dto/response/AdminLoginResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/dto/response/AdminSignupResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/dto/response/DashboardStatsResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/dto/response/ModifyRoleResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/service/AdminService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/controller/UserController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/UserService.java
  service/main-server/src/main/resources/static/.well-known/appspecific/com.chrome.devtools.json
  service/main-server/src/main/resources/static/favicon.ico
  service/main-server/src/main/resources/templates/admin/dashboard.html
  service/main-server/src/main/resources/templates/admin/events.html
  service/main-server/src/main/resources/templates/admin/fragments/layout.html
  service/main-server/src/main/resources/templates/admin/login.html
  service/main-server/src/main/resources/templates/admin/signup.html
  service/main-server/src/main/resources/templates/admin/tickets.html
  service/main-server/src/main/resources/templates/admin/users.html
  service/user/src/main/java/org/codenbug/user/security/config/SecurityConfig.java
Labels: feat

#230 Test/행사 조회 테스트 분리
  service/common/build.gradle
  service/main-server/src/main/java/org/codeNbug/mainserver/MainServerApplication.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/controller/EventController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/EventInfoResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/request/EventListFilter.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/CostRange.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/DateRangeValidator.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/Event.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/ValidDateRange.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/config/AppConfig.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/event/controller/EventControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/event/controller/EventIntegrationTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/event/service/CommonEventServiceTest.java
Labels: test

#233 fix: 가능한 좌석수 세기 수정
  service/common/src/main/java/org/codenbug/common/util/CookieUtil.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/QueryDslCommonEventRepository.java
  service/main-server/src/main/resources/static/payment/payment.html
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/event/repository/QueryDslCommonEventRepositoryTest.java
Labels: bug

#232 Test/매니저 단위 테스트
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/service/EventRegisterServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/service/ManagerPurchasesServiceTest.java
Labels: enhancement

#236 Refactor/좌석테스트 로직분리
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/dto/SeatLayoutResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/exception/GlobalExceptionHandler.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/exception/globalException/ConflictException.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/purchase/controller/PurchaseControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/seat/controller/SeatControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/seat/service/SeatServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/util/BaseTestUtil.java
Labels: test, refactoring

#239 Bug: 예매 가능 좌석 수 조회 실패
  .github/workflows/disptach-ci.yml
  .github/workflows/main-ci.yml
  .github/workflows/queue-ci.yml
  service/common/src/main/java/org/codenbug/common/util/CookieUtil.java
Labels: bug

#244 feat: 행사 리스트 조회시 최소가격과 최대가격을 표시하도록 수정
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/response/EventListResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/CommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/QueryDslCommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/CommonEventService.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/event/repository/QueryDslCommonEventRepositoryTest.java
  service/main-server/src/test/resources/application-test.yml
Labels: feat

#245 Test: 알림 테스트 로직 분리
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/notification/controller/NotificationControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/notification/controller/NotificationIntegrationTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/notification/service/NotificationServiceTest.java
Labels: test, refactoring

#247 Feat: CI/CD 파이프라인에 push 이벤트 추가
  .github/workflows/disptach-ci.yml
  .github/workflows/main-ci.yml
  .github/workflows/queue-ci.yml
Labels: chore

#249 Refactor/구매테스트 로직분리
  .github/workflows/main-ci.yml
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/RedisLockService.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/purchase/controller/PurchaseControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/seat/controller/SeatControllerTest.java
Labels: test, refactoring

#251 Test/매니저 기능 테스트 추가
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/controller/ManagerController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventEditService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventRegisterService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/ManagerEventSearchService.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/service/EventDeleteServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/service/EventRegisterServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/service/ManagerEventSearchServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/service/ManagerPurchasesServiceTest.java
Labels: enhancement

#235 Feat: 관리자 대시보드
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/controller/AdminController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/dto/response/EventAdminDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/dto/response/TicketAdminDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/service/AdminService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/repository/EventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/ticket/repository/TicketRepository.java
  service/main-server/src/main/resources/templates/admin/event-detail.html
  service/main-server/src/main/resources/templates/admin/events.html
  service/main-server/src/main/resources/templates/admin/fragments/layout.html
  service/main-server/src/main/resources/templates/admin/monitoring.html
  service/main-server/src/main/resources/templates/admin/tickets.html
Labels: feat

#257 Chore: 의존성 추가 및 테스트 설정 업데이트
  .github/workflows/common-ci.yml
  .github/workflows/disptach-ci.yml
  .github/workflows/main-ci.yml
  .github/workflows/queue-ci.yml
  build.gradle
  service/main-server/build.gradle
  service/message-dispatcher/build.gradle
  service/message-dispatcher/src/main/resources/application-prod.yml
  service/message-dispatcher/src/main/resources/application.yml
  service/queue-server/build.gradle
  service/queue-server/src/main/resources/application-prod.yml
  service/queue-server/src/main/resources/application.yml
  service/queue-server/src/test/java/org/codeNbug/queueserver/QueueServerApplicationTests.java
  service/user/build.gradle
  service/user/src/test/java/org/codenbug/user/UserApplicationTests.java
Labels: chore

#259 Test: 사용자 테스트
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/user/business/PurchaseServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/user/business/UserServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/user/controller/UserControllerTest.java
Labels: test

#276 Feat/batch event update
  service/main-server/build.gradle
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/batch/EventStatusUpdateBatchConfig.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/JpaCommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/EventStatusUpdateScheduler.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/config/BatchConfig.java
  service/main-server/src/main/resources/application.yml
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/event/controller/EventControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/purchase/controller/PurchaseControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/seat/controller/SeatControllerTest.java
  service/main-server/src/test/resources/application-test.yml
Labels: enhancement

#280 feat: Manager - EventRegisterService 에서 이벤트 초기 상태 저장
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventRegisterService.java
Labels: enhancement

#285 Feat: 관리자 대시보드
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/controller/AdminController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/service/AdminService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/batch/EventStatusUpdateBatchConfig.java
  service/main-server/src/main/resources/templates/admin/events.html
Labels: feat

#287 Feat: EventInfoResponse에 prices 추가 및 SeatDto 구조 변경
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/EventInfoResponse.java
Labels: feat

#290 행사 리스트 최대최소가격 null 나오는 버그 해결과 행사 리스트 페이지네이션
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/controller/EventController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/entity/CommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/repository/QueryDslCommonEventRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/CommonEventService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/config/AppConfig.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/event/controller/EventControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/event/service/CommonEventServiceTest.java
Labels: bug

#272 Refactor: 사용자 기능
  service/main-server/src/main/java/org/codeNbug/mainserver/MainServerApplication.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/controller/AdminController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/dto/request/AdminSignupRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/service/AdminService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/controller/UserController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/EmailService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/LoginAttemptService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/UserEmailService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/UserSchedulerService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/UserService.java
  service/main-server/src/main/resources/application.yml
  service/main-server/src/main/resources/templates/account-expiration-warning.html
  service/main-server/src/main/resources/templates/admin/fragments/layout.html
  service/main-server/src/main/resources/templates/admin/settings.html
  service/main-server/src/main/resources/templates/password-expiration-warning.html
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/user/business/UserServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/user/controller/UserControllerTest.java
  service/user/src/main/java/org/codenbug/user/domain/user/entity/User.java
  service/user/src/main/java/org/codenbug/user/domain/user/repository/UserRepository.java
  service/user/src/main/java/org/codenbug/user/security/service/CustomUserDetails.java
  service/user/src/main/java/org/codenbug/user/security/service/SnsUserDetails.java
  service/user/src/main/java/org/codenbug/user/sns/Entity/SnsUser.java
Labels: feat, refactoring

#281 Refactor: 알림 이벤트 처리 구조 개선
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/dto/NotificationEventDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/repository/NotificationRepository.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/service/NotificationEventService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/service/NotificationService.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/notification/service/NotificationRealTimeServiceTest.java
Labels: refactoring

#293 bug: 이메일 인증 오류 로직 수정
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/EmailService.java
Labels: bug

#298 fix: s3 url 발급 시 이미지 파일의 확장자로 content-type 설정하도록 함.
  service/main-server/src/main/java/org/codeNbug/mainserver/external/image/service/S3PresignedUrlService.java
Labels: bug

#283 Fix/좌석 성능개선
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventDeleteService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventEditService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventRegisterService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/controller/SeatController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/RedisListenerService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatTransactionService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/Redis/config/RedisConfig.java
  service/main-server/src/test/java/org/codeNbug/mainserver/TestConfig.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/service/EventDeleteServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/service/EventRegisterServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/notification/controller/NotificationIntegrationTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/purchase/controller/PurchaseControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/purchase/controller/PurchaseIntegrationTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/seat/controller/SeatControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/seat/controller/SeatIntegrationTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/seat/service/SeatServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/util/BaseTestUtil.java
Labels: test, refactoring

#300 Feat: serverTimeZone 설정
  service/main-server/Dockerfile
Labels: feat

#303 fix: jackson 직렬화에 KST 사용하도록 설정 변경
  service/main-server/src/main/resources/application.yml
Labels: bug

#307 refactor: 다건 알림 삭제 API
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/controller/NotificationController.java
Labels: refactoring

#299 Refactor: redis 및 db 최적화
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/controller/AdminController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/service/AdminService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/LoginAttemptService.java
  service/main-server/src/main/resources/templates/admin/settings.html
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/user/controller/UserControllerTest.java
Labels: refactoring

#315 Feat/버전별 배포 가능하도록 수정-2
  .github/workflows/deploy.yml
Labels: chore

#313 Refactor: 다건 알림 api 수정
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/controller/NotificationController.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/notification/controller/NotificationControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/notification/controller/NotificationIntegrationTest.java
Labels: refactoring

#316 Feat: 알림에 title 필드 추가
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/admin/service/AdminService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventDeleteService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/service/EventEditService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/controller/NotificationController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/dto/NotificationCreateRequestDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/dto/NotificationDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/dto/NotificationEventDto.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/entity/Notification.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/notification/service/NotificationService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseService.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/notification/controller/NotificationControllerTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/notification/controller/NotificationIntegrationTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/notification/service/NotificationRealTimeServiceTest.java
Labels: feat, test

#318 Fix/좌석 조회 redis 버그
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatTransactionService.java
Labels: bug

#320 fix: utc -> kst 변환 deserializer 추가 및 event register request dto 에 적용
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/manager/dto/EventRegisterRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/config/TimeZoneConfig.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/util/UtcToKstLocalDateTimeDeserializer.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/manager/controller/ManagerControllerTest.java
Labels: bug

#330 Fix: 좌석 TTL 만료 후 Redis Cache에 있는 좌석 정보 삭제
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/RedisListenerService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/SeatTransactionService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/Redis/config/RedisConfig.java
Labels: bug

#334 Fix: 순환참조 버그 해결
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/seat/service/RedisListenerService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/global/Redis/config/RedisConfig.java
Labels: bug

#333 Fix: 환불 dto에 paymentKey 추가
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/dto/PurchaseHistoryDetailResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseService.java
Labels: bug

#337 Fix: 유저 개인정보 수정
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/controller/UserController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/dto/request/UserUpdateRequest.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/user/service/UserService.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/user/business/UserServiceTest.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/user/controller/UserControllerTest.java
  service/user/src/main/java/org/codenbug/user/domain/user/entity/User.java
  service/user/src/main/java/org/codenbug/user/sns/Entity/SnsUser.java
Labels: bug

#341 Fix: paymentKey log 추가
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/purchase/service/PurchaseService.java
Labels: bug

#346 Feat/메인페이지 추천 이벤트 추가
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/controller/EventController.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/dto/response/EventListResponse.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/CommonEventService.java
  service/main-server/src/main/java/org/codeNbug/mainserver/domain/event/service/EventViewCountUpdateScheduler.java
  service/main-server/src/test/java/org/codeNbug/mainserver/domain/event/service/CommonEventServiceTest.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/service/WaitingQueueEntryService.java
Labels: feat

#348 feat: static file로 카테고리 이미지 추가
  service/main-server/src/main/resources/static/imgs/concert.png
  service/main-server/src/main/resources/static/imgs/etc.png
  service/main-server/src/main/resources/static/imgs/exhibition.png
  service/main-server/src/main/resources/static/imgs/fanMeeting.png
  service/main-server/src/main/resources/static/imgs/musical.png
  service/main-server/src/main/resources/static/imgs/sports.png
  service/user/src/main/java/org/codenbug/user/security/config/SecurityConfig.java
Labels: feat

#352 feat: db 풀 갯수 조정
  service/main-server/src/main/resources/application-prod.yml
  service/queue-server/src/main/resources/application-prod.yml
Labels: feat

#363 Hotifx: sse메시지에 대기열 상태 표시하도록 수정
  service/queue-server/src/main/java/org/codeNbug/queueserver/external/redis/EntryStreamMessageListener.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/entity/Status.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/service/SseEmitterService.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/thread/QueueInfoScheduler.java
Labels: enhancement

#368 Hotfix: 대기열 중간에 나간 유저를 순번에서 카운팅하도록 수정
  service/message-dispatcher/src/main/java/org/codenbug/messagedispatcher/thread/EntryPromoteThread.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/service/SseEmitterService.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/service/WaitingQueueEntryService.java
  service/queue-server/src/main/java/org/codeNbug/queueserver/waitingqueue/thread/QueueInfoScheduler.java
Labels: bug
